theme: jekyll-theme-cayman
title: <img src = "https://raw.githubusercontent.com/zeltagq/docs/master/logo.png" alt = "Zelta">
description: <br><br><img src = "https://img.shields.io/badge/version-0.5%20Î²-purple.svg" alt = "version" height="10px" width="10px"> &nbsp <img src = "https://img.shields.io/npm/dw/zelta" alt = "downloads"> &nbsp <img src = "https://img.shields.io/badge/made%20with-Node%20JS-yellow.svg" alt = "made-with"> &nbsp <img src = "https://img.shields.io/badge/server-Ireland-orange.svg" alt = "server"> &nbsp <img src = "https://img.shields.io/badge/status-Up-darkgreen.svg" alt = "status">
github:
  is_project_page: false
