theme: jekyll-theme-cayman
title: <img src = "https://raw.githubusercontent.com/zeltagq/docs/master/logo.png" alt = "Zelta">
description: 'CURRENT VERSION : v0.5 Î²  |  SERVERS : Ireland  |  STATUS : Up'
github:
  is_project_page: false
