theme: jekyll-theme-cayman
title: <img src = "https://raw.githubusercontent.com/zeltagq/docs/master/logo.png" alt = "Zelta">
description: [![made-with-node](https://img.shields.io/badge/made%20with-Node%20JS-green.svg)](https://nodejs.org/en/)
github:
  is_project_page: false
